--- 
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: mattermost
  namespace: gitlab
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: mattermost
      annotations: 
          pod.boostport.com/vault-approle: gitlab-mattermost
          pod.boostport.com/vault-init-container: install
          pod.beta.kubernetes.io/init-containers: '[
              {
                "name": "install",
                "image": "boostport/kubernetes-vault-init:0.2.0",
                "imagePullPolicy": "IfNotPresent",
                "env": [
                  {
                    "name": "VAULT_ROLE_ID",
                    "value": "f3357628-90bf-65d1-fc62-897e159f82ad"
                  },
                  {
                    "name": "CREDENTIALS_PATH",
                    "value": "/secrets"
                  }
                ],
                "volumeMounts": [
                  {
                    "name": "vault-token",
                    "mountPath": "/secrets"
                  }
                ]
              }
            ]'
    spec:
      volumes:
      - name: vault-token
        emptyDir: {}
      containers: 
      - image: nebtex/mattermost-docker
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        name: mattermost
        env:
        - name: CONSUL_HTTP_ADDR
          value: consul.kv:8500
        - name: APP_NAME
          value: mattermost
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: vault-token
          mountPath: /secrets
        
